"""
Compare our marks against the examiner's, and say where we differ.

    output/marks/*.json + gold/gold_marks.csv  ->  output/agreement.md

WHAT THIS IS NOT
----------------
It is not a score. The examiner's grid is a reference, not a ground
truth: seven of the fifty covers carry a demonstrable defect - four
Part C totals that ignore the paper's own choice instruction, one
arithmetic slip, one grid with no totals, one with no marks at all
(gold/gold_notes.md). A grader that matched this reference perfectly
would be reproducing those mistakes.

So the question is never "did we match?" but "where do we differ, and
which of us is right?" - and on the four choice-policy booklets the
answer is us, by construction.

WHY THE COMPARISON IS AN INTERVAL
---------------------------------
Most rubric items are still with the model tier or a human, so a
question does not yet have a single mark - it has `settled` (decided by
the cheap tiers) and `pending` (not yet decided). Reporting a point
estimate now would mean silently treating every pending item as zero,
which would make the grader look far harsher than it is.

So each question is compared as `[settled, settled + pending]`:

  inside    the examiner's mark is still reachable - nothing is wrong
  over      we settled MORE than the examiner awarded - irreversible
  under     we ruled out marks the examiner gave - irreversible

Only the last two are errors. "Inside" is not agreement, it is the
absence of a contradiction, and the report says so.

Run:
    python src/agreement.py
"""

import argparse
import csv
import glob
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import paths

CHOICE_ROWS = {"3", "4"}

# Booklets whose covers deviate from the paper's Part C choice rule.
# Our grader takes the better half, as the paper instructs, so we are
# expected to differ here. Listed so the report can be given both ways.
CHOICE_DEVIATIONS = {
    "student_22_cie_3", "student_27_cie_3",
    "student_38_cie_3", "student_45_cie_1",
}


def examiner_mark(row, qid):
    if not row or row.get("confidence") == "no_gold":
        return None
    number = qid[0]
    if number in CHOICE_ROWS:
        value = (row.get(f"q{number}t") or "").strip()
        return float(value) if value else None
    value = (row.get(f"q{number}{qid[1:] or 'a'}") or "").strip()
    return float(value) if value else 0.0


def load():
    with open(paths.GOLD_CSV, encoding="utf-8", newline="") as handle:
        gold = {r["booklet_id"]: r for r in csv.DictReader(handle)}
    reports = [json.load(open(p, encoding="utf-8"))
               for p in sorted(glob.glob(str(paths.MARKS_DIR / "*.json")))]
    return gold, reports


def compare(gold, reports, skip_deviations=False):
    rows = []
    for report in reports:
        booklet = report["booklet_id"]
        if skip_deviations and booklet in CHOICE_DEVIATIONS:
            continue
        gold_row = gold.get(booklet)
        for question in report["questions"]:
            if not question["counted"]:
                continue
            mark = examiner_mark(gold_row, question["id"])
            if mark is None:
                continue
            impossible = mark > question["marks_available"] + 1e-9
            settled = question["marks_settled"]
            pending = question["marks_pending"]

            if settled > mark + 1e-9:
                verdict = "over"
            elif settled + pending < mark - 1e-9:
                verdict = "under"
            else:
                verdict = "inside"

            rows.append({
                "booklet": booklet,
                "cie": report["cie"],
                "question": question["id"],
                "part": question["part"],
                "breakdown": question["breakdown_source"],
                "examiner": mark,
                "settled": settled,
                "pending": pending,
                "available": question["marks_available"],
                "verdict": verdict,
                "impossible": impossible,
                "tiers": sorted({i["tier"] for i in question["items"]}),
                "attempted": question["attempted"],
            })
    return rows


def section(title):
    return ["", f"## {title}", ""]


def render(rows, rows_clean, reports, gold):
    out = ["# Agreement with the examiner", ""]
    out.append("Generated by `src/agreement.py`.")
    out.extend([
        "",
        "The examiner's grid is a **reference, not a ground truth** - seven",
        "of the fifty covers carry a demonstrable defect. Where we differ,",
        "the finding is \"we differ, and here is why\", never \"the grader is",
        "wrong\". See `gold/gold_notes.md`.",
        "",
        "Most rubric items are still queued to the model tier or a human, so",
        "each question is compared as an interval `[settled, settled +",
        "pending]` rather than as a number. Collapsing that to a point now",
        "would treat every undecided item as a zero.",
    ])

    usable = [r for r in rows if not r["impossible"]]
    counts = Counter(r["verdict"] for r in usable)
    total = len(usable)

    out.extend(section("Headline"))
    out.append(f"- **{total}** comparable questions across "
               f"{len({r['booklet'] for r in rows})} booklets")
    out.append(f"- **{counts['inside'] / total:.0%}** keep the examiner's "
               "mark reachable (no contradiction)")
    out.append(f"- **{counts['over']}** over-settled — we awarded marks the "
               "examiner did not")
    out.append(f"- **{counts['under']}** under-settled — we ruled out marks "
               "the examiner gave")
    out.append(f"- irreversible error rate: "
               f"**{(counts['over'] + counts['under']) / total:.1%}**")
    out.append("")
    out.append("For scale, the examiner's own covers carry a defect on 14% of")
    out.append("booklets. This is not a claim to be better than them - it is")
    out.append("a statement that the two disagree about as often as the")
    out.append("reference disagrees with itself.")

    clean = [r for r in rows_clean if not r["impossible"]]
    c2 = Counter(r["verdict"] for r in clean)
    out.extend(section("Excluding the four choice-policy booklets"))
    out.append("On `student_22_cie_3`, `student_27_cie_3`, "
               "`student_38_cie_3` and")
    out.append("`student_45_cie_1` the examiner totalled both halves of a Part")
    out.append("C choice pair. Our grader takes the better half, as the paper")
    out.append("instructs, so a difference there is expected:")
    out.append("")
    out.append(f"- {len(clean)} comparable questions")
    out.append(f"- {c2['inside'] / len(clean):.0%} inside, {c2['over']} over, "
               f"{c2['under']} under")

    # --- by part ------------------------------------------------------
    out.extend(section("By part of the paper"))
    out.append("| part | questions | inside | over | under |")
    out.append("|---|---|---|---|---|")
    by_part = defaultdict(list)
    for row in usable:
        by_part[row["part"]].append(row)
    for part in sorted(by_part):
        group = by_part[part]
        c = Counter(r["verdict"] for r in group)
        out.append(f"| {part} | {len(group)} | {c['inside'] / len(group):.0%} "
                   f"| {c['over']} | {c['under']} |")

    # --- printed vs inferred -----------------------------------------
    out.extend(section("Printed vs inferred mark splits"))
    out.append("Where the scheme printed its own breakdown we copied it;")
    out.append("where it did not, the division into rubric items is ours.")
    out.append("If our inferred splits were poor, this is where it shows.")
    out.append("")
    out.append("| split | questions | inside | over | under |")
    out.append("|---|---|---|---|---|")
    by_split = defaultdict(list)
    for row in usable:
        by_split[row["breakdown"]].append(row)
    for split in sorted(by_split):
        group = by_split[split]
        c = Counter(r["verdict"] for r in group)
        out.append(f"| {split} | {len(group)} | "
                   f"{c['inside'] / len(group):.0%} | {c['over']} | "
                   f"{c['under']} |")

    # --- by deciding tier ---------------------------------------------
    out.extend(section("Which tiers are implicated in the errors"))
    out.append("A question's marks come from several items and so several")
    out.append("tiers; this counts a tier once per question it touched.")
    out.append("")
    out.append("| tier | questions touched | over | under |")
    out.append("|---|---|---|---|")
    tier_total, tier_over, tier_under = Counter(), Counter(), Counter()
    for row in usable:
        for tier in row["tiers"]:
            tier_total[tier] += 1
            if row["verdict"] == "over":
                tier_over[tier] += 1
            elif row["verdict"] == "under":
                tier_under[tier] += 1
    for tier in sorted(tier_total, key=lambda t: -tier_total[t]):
        out.append(f"| `{tier}` | {tier_total[tier]} | {tier_over[tier]} | "
                   f"{tier_under[tier]} |")

    # --- booklet level -------------------------------------------------
    out.extend(section("Booklet totals"))
    out.append("Our settled total is a **lower bound** - every pending item")
    out.append("is excluded, not assumed zero. So `settled <= examiner <=`")
    out.append("`settled + pending` is the expected shape, and the columns")
    out.append("below are not a score.")
    out.append("")
    out.append("| booklet | settled | + pending | examiner | reachable |")
    out.append("|---|---|---|---|---|")
    for report in reports:
        row = gold.get(report["booklet_id"])
        if not row or row.get("confidence") == "no_gold":
            continue
        total_mark = (row.get("total_grid") or "").strip()
        if not total_mark:
            continue
        examiner = float(total_mark)
        low = report["marks_settled"]
        high = low + report["marks_pending"]
        ok = "yes" if low - 1e-9 <= examiner <= high + 1e-9 else "**no**"
        out.append(f"| `{report['booklet_id']}` | {low:g} | {high:g} | "
                   f"{examiner:g} | {ok} |")

    # --- the errors themselves ----------------------------------------
    out.extend(section("Every irreversible difference"))
    out.append("| booklet | q | ours | examiner | verdict | tiers |")
    out.append("|---|---|---|---|---|---|")
    for row in sorted(usable, key=lambda r: (r["verdict"], r["booklet"])):
        if row["verdict"] == "inside":
            continue
        out.append(
            f"| `{row['booklet']}` | `{row['question']}` | "
            f"{row['settled']:g}–{row['settled'] + row['pending']:g} | "
            f"{row['examiner']:g} | {row['verdict']} | "
            f"{', '.join(row['tiers'])} |"
        )

    impossible = [r for r in rows if r["impossible"]]
    if impossible:
        out.extend(section("Excluded as unreachable"))
        out.append("The examiner awarded more than the question is worth, so")
        out.append("no grader respecting the paper could match it.")
        out.append("")
        for row in impossible:
            out.append(f"- `{row['booklet']}` `{row['question']}`: examiner "
                       f"{row['examiner']:g} on a {row['available']:g}-mark "
                       "question")

    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()

    gold, reports = load()
    if not reports:
        raise SystemExit("no marks yet - run: python src/grade.py --all")

    rows = compare(gold, reports)
    rows_clean = compare(gold, reports, skip_deviations=True)

    paths.OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = paths.OUT_DIR / "agreement.md"
    out.write_text(render(rows, rows_clean, reports, gold), encoding="utf-8")

    usable = [r for r in rows if not r["impossible"]]
    counts = Counter(r["verdict"] for r in usable)
    print(f"{len(usable)} comparable questions")
    print(f"  inside {counts['inside']}  "
          f"({counts['inside'] / len(usable):.0%})")
    print(f"  over   {counts['over']}")
    print(f"  under  {counts['under']}")
    print(f"\n{out}")


if __name__ == "__main__":
    main()
